name: logic-translation
version: 0.0.1
synopsis: Translation from FOL to LTL+Past and LTL, via separation of LTL+Past
maintainer: Daniel Rebelo de Oliveira <drdo@drdo.eu>
license: LGPL-3
github: drdo/logic-translation
category: Logic

dependencies:
  - base >= 4.8 && < 5
  - bytestring >= 0.10 && < 0.11 # No idea what version we actually need
  - containers
  - deepseq
  - parsec >= 3 && < 4 # No idea what version we actually need
  - pretty
  - text >= 1 # No idea what version we actually need
  - utf8-string >= 1 # No idea what version we actually need

library:
  source-dirs: library
  exposed-modules:
    - BooleanCombination
    - TL
    - FOMLO
    - Parse
    - Pretty
    - Separation
    - Translation

executable:
  source-dirs: executable
  main: Main.hs
  dependencies:
    - logic-translation
